---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: auth-service
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: auth-env
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-env
data:
  DEBUG: "True"
  SECRET_KEY: qwertyytrewq
  DB_NAME: authdb
  DB_USER: postgres
  DB_PASSWORD: postgres
  DB_HOST: db
  DB_PORT: "5432"
