name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: Build and push Docker image
        run: |
          docker build -t <your-aws-ecr-repo-uri>:latest .
          aws ecr get-login-password | docker login --username AWS --password-stdin <your-aws-ecr-repo-uri>
          docker push <your-aws-ecr-repo-uri>:latest

      - name: Deploy to EKS with kubectl or Helm
        run: |
          # Use kubectl apply -f or helm upgrade --install here
